site_name: GWBASE
site_description: An Algorithm for Assessing the Impact of Groundwater Decline on Baseflow in US Streams
site_author: Xueyi Li, Norman L. Jones, Gustavious P. Williams, Amin Aghababaei, Riley C. Hales
site_url: https://gwbase.readthedocs.io/

repo_url: https://github.com/BYU-Hydroinformatics/gwbase.git
repo_name: gwbase

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - bash

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Data Guide: data-guide.md
  - User Guide:
    - Process Overview: overview.md
    - Code Organization: code-organization.md
    - Running the Code: running-the-code.md
  - API Reference: api-reference.md
